# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NewRaptor4
                                 A QGIS plugin
 Add a new raptor nest, create Buffer, and impact table
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-31
        copyright            : (C) 2025 by M M LLC
        email                : abc@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NewRaptor4 class from file NewRaptor4.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .new_raptor import NewRaptor4
    return NewRaptor4(iface)
